### ISSUE TITLE
Generated Code Issue

### ISSUE THREAD

**Issue by 0xCalibur** [wighawag/forge-deploy#1]
Hi!

Been waiting for such a tool. Made something with JQ latest.json parsing a while back but never really work because some contract doesn't have the name when it's all immutable field for example.

Here is the issue I reported to foundry a while back.
https://github.com/foundry-rs/foundry/issues/4169

So anyway, wanted to give your take a try!
I'm having issues with the generate code, doesn't seem to compile because it doesn't generate the return value correctly.
Here is a branch where I'm starting to test it with our repo.
 
you run `make init` and then `make` to reproduce.

https://github.com/Abracadabra-money/abracadabra-money-foundry/pull/71

Thanks :)

**Comment by wighawag** [comment]
Hey, thanks for trying out and reporting the issue.

I fixed it (plus support for skipping abstract) in v0.0.29

The tool is currently using regex to find the contracts and there was some issues in one of them. Planning to change that if I can find a good parser or use forge artifact (but the forge artifact had some issues)

Note that your project will still fails as currently forge-deploy comes in with a contract called `Proxy` which conflict with your use of openzeppelin

If you make this a named import : https://github.com/Abracadabra-money/abracadabra-money-foundry/blob/3b1725737b7721b7d302eb3a9ef441ee9bf8b250/utils/BaseScript.sol#L5

like this:

```
import {DeployerFunctions} from "generated/deployer/DeployerFunctions.g.sol";
```

then you should be good to go

**Comment by wighawag** [comment]
Oh actually I broke something else with the use of named import. Please bear with me :D

**Comment by wighawag** [comment]
Ok got it something working in v0.0.30, it still goes back to global import and so for your case there is a failing case with 

```
Compiler run failed
error[2333]: DeclarationError: Identifier already declared.
   --> generated/deployer/DeployerFunctions.g.sol:153:1:
    |
153 | import  "src/periphery/TriCryptoUpdator.sol";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> src/interfaces/ICurvePool.sol:72:1:
   |
72 | interface ITriCrypto is ICurvePool {
   | ^ (Relevant source part starts here and spans across multiple lines).
```

I ll look into generating multiple files instead to avoid these. but I suspect you can workaround this by extracting the interface ?

**Comment by wighawag** [comment]
There are other issues in the repo with run being override and the deployer function name which you shpould be able to re-arange

Happy to help out if you find issues with forge-deploy after these are ressolved

**Comment by wighawag** [comment]
v0.0.32 is much better, I now namespace the import, so no conflict

it is not yet full proof if some of your type name start with `ufixed` or `fixed` but for your repo, this is not an issue

**Comment by wighawag** [comment]
as for your override errors, you'l need to use

```
function deploy() external returns (CauldronFeeWithdrawer withdrawer) {
```

instead of
```
function run() public returns (CauldronFeeWithdrawer withdrawer) {
```

**Comment by 0xCalibur** [comment]
thanks for all the updates, will try this asap. Btw I get the feeling you'll get into the same issue i've been facing with https://github.com/foundry-rs/foundry/issues/4169 since you are relying on the run-latest contract name, don't you think?

**Comment by wighawag** [comment]
I created a PR : https://github.com/Abracadabra-money/abracadabra-money-foundry/pull/72
it compiles there :)

**Comment by wighawag** [comment]
> Btw I get the feeling you'll get into the same issue i've been facing with https://github.com/foundry-rs/foundry/issues/4169 since you are relying on the run-latest contract name, don't you think?

forge-deploy do not use the contract name, it handle the mapping between deployment and artifact by itself using the return field of the script
