### ISSUE TITLE
Deployment fails with `0.2.0`

### ISSUE THREAD

**Issue by BarakChamo** [wighawag/forge-deploy#10]
Deployment fails with:
```
Error: 
Failed to deploy script:
Execution reverted: EvmError: Revert (gas: 148220)
```

After running:
`DEPLOYMENT_CONTEXT=localhost forge script deploy/Deploy.s.sol --rpc-url http://127.0.0.1:8545 --broadcast --private-key ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 -v && forge-deploy sync;`

Using default anvil `private-key`.

Generated deployer script:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-deploy/DeployScript.sol";
import "../build/deployer/DeployerFunctions.g.sol";

contract Deployments is DeployScript {
    using DeployerFunctions for Deployer;

    function deploy() external returns (Counter) {
        return deployer.deploy_Counter("Counter");
    }
}

```

**Comment by BarakChamo** [comment]
Hi @wighawag 

I just used the output params for `gen-deployer`:
```
"gen-deployer": "yarn forge-deploy gen-deployer --output ./build --sources ./contracts/src",
```

**Comment by wighawag** [comment]
ok, make sense can't really see anything wrong with what you posted.

if you could isolate the issue in a separate repo that would great, else maybe send the verbose output to have more info where it fails

if you look at the generated deploy function it is quite simple, maybe try to isolate some code to see what fails

**Comment by wighawag** [comment]
Thanks for that

the issue is that for now, forge-deploy assume the `out` folder is in `./out`

so if you remove `out = 'build/out'` from foundry.toml it works

**Comment by BarakChamo** [comment]
Hi @wighawag 

Thanks for taking a look, I actually managed to make things work with the `build` folder in place.

I was curious reading your reply and kept poking around, the solution was adding read rights to the correct folder:

```
# replace this
{ access = "read", path = "./out"},

# with this
{ access = "read", path = "./build/out"},
```

It was misconfigured for my setup but the forge error was a little opaque.

Thanks for your help!

**Comment by BarakChamo** [comment]
Just thought I'd add that the last step to get sync working was to direct the sync at the correct location for aritfacts.

In my case:
`forge-deploy sync --artifacts ./build/out`
