### ISSUE TITLE
Suggestion: deployments save like hardhat-deploy

### ISSUE THREAD

**Issue by 0xCalibur** [wighawag/forge-deploy#2]
Would be nice to have something similar like deployments.save had with hardhat-deploy. In case some contract call creates a new contract, I was using it to label it and in some case attach an abi to it so it goes in the deployment file.

example:
https://github.com/Abracadabra-money/magic-internet-money/blob/23266d17969a95e69199670cba9d0060bff33340/archive/deploy/FTMDegenCauldron.ts#L55

**Comment by wighawag** [comment]
you can : https://github.com/wighawag/forge-deploy/blob/f38bcd71d045f78827ad7b25810eb83b4496ef40/contracts/Deployer.sol#L197-L223

need to document and maybe you were thinking of a nicer api ?

technically you could put empty bytecode and args if you dot care about them
but maybe I should add a simpler methods like 

```
function save( string memory name, address deployed, string memory artifact) external;
function save( string memory name, address deployed, string memory artifacts, bytes memory args) external;
```

**Comment by 0xCalibur** [comment]
I'm dumb, didn't think you had it yet. Insane work ser, will give it a try.

**Comment by wighawag** [comment]
I updated the save function

it is a breaking change (I reordered the args), I try to avoid them if I can but prefer to do that now as we are still early :)

https://github.com/wighawag/forge-deploy/blob/main/docs/src/contracts/Deployer.sol/contract.Deployer.md#save

**Comment by 0xCalibur** [comment]
Thanks for the update. Trying it out but I'm facing two issues reproductible with the current `forge-deploy-testing` branch of my repo.

The issues can be reproduced using `make init` first and then `SCRIPT=ConvexCauldrons make mainnet-deploy-simulation`
This should deploy the content of `ConvexCauldrons.s.sol`

First issue is when using `deployer.save` using an interface artifact. I understand that an interface artifacts doesn't contain any bytecode but do you think there could be a neat way to create a deployment with `wrapper` created from `            wrapper = IConvexWrapper(wrapperFactory.CreateWrapper(38));`?

<img width="663" alt="image" src="https://user-images.githubusercontent.com/92554750/235763690-38970474-0bc2-4dd3-9c93-b62627b1d1ca.png">

Second issue, if you comment out the `deployer.save` line, to bypass the first issue, is related to zero byte contract being deployed. It's a similar issue I've been facing with that issue I've reported to foundry back then when I was trying to get the `contractName` from `run-latest.json`, seems like it's having trouble when all the fields are immutable? Or I might be wrong?
<img width="659" alt="image" src="https://user-images.githubusercontent.com/92554750/235763912-857ad7fd-0284-4195-bf68-f809671b36e7.png">

**Comment by wighawag** [comment]
For the first one, forge-deploy assume you are using the short save version as you just been using the artifact and so the bytecode will be fetched from the given artifact

if you do not you can use
```solidity
deployer.save("TrycriptoAbraConvexWrapper", address(wrapper), "IConvexWrapper.sol:IConvexWrapper", "", "");
```

Thinking to maybe do a try catch for `getCode` but for now, I ll leave this as is. Need to think more of the implications

For the second one, not sure what it is. this is happening in the simulation, not in forge-deploy reading of run-latest

Do you know where in the code this trace is associated with ?

**Comment by 0xCalibur** [comment]
About the second issue. I'm not sure, the wrapper address is the right one, so `.curveToken()` should work. I get the impression it might be the issue again when a contract has only immutable fields versus using the artifacts.

Here you can see the same code, one using vanilla `new` and the other using `deployer` but the second is reverting on simulation.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/92554750/235923780-bdeebb06-ced2-4556-84bc-674850ea4df2.png">

**Comment by wighawag** [comment]
I wonder why there is `staticcall` could be the issue

**Comment by wighawag** [comment]
Does not feel like a forge-deploy issue

So I guess if you use new and save the deployment via `deployer.save` then it should workaround the issue ?

**Comment by 0xCalibur** [comment]
> Does not feel like a forge-deploy issue
> 
> So I guess if you use new and save the deployment via `deployer.save` then it should workaround the issue ?

that could be a workaround but it's annoying to have to repeat the constructor args twice, unless I just skip specifying them with ""

**Comment by wighawag** [comment]
Oh yes i agree
Would be cool to make an minimal repo, as i dont think it ks related to forge-deploy 

Another way to fix is to modify the template to use `new`

With forge-deploy you can provide your own with --templates <template folder> and you can copy the one from forge-deploy repo to get started

**Comment by wighawag** [comment]
Something like this : https://gist.github.com/wighawag/081e9d1fe14f2f17c477eaa8f1253c5a

(not tested)

**Comment by wighawag** [comment]
Ha actually the weird thing is that it should actually fails, see the interface : https://github.com/Abracadabra-money/abracadabra-money-foundry/blob/3bd89b0b39e1b18450bc4de500f1cdd2b3a0fd76/src/interfaces/IConvexWrapper.sol#L36

it define curveToken as a view function so solidity compiler will use a static call

Could it be that when you use new, the failure get caught somehow. 

This is weird, but I know see why there is a `staticcall` in the trace

**Comment by wighawag** [comment]
https://etherscan.io/address/0xB0daC09364550ecdFc46D9C4e012F2FABE70BC56#readContract

Ha, this does not seem to have a curveToken function

**Comment by 0xCalibur** [comment]
> https://etherscan.io/address/0xB0daC09364550ecdFc46D9C4e012F2FABE70BC56#readContract
> 
> Ha, this does not seem to have a curveToken function

thanks for the help, 0xB0da has been deployed 3h ago by convex, wrapped is created by a proxy they provided us, if I run the simulation again it might give a new address this time. I'll give it another try asap but it should create a wrapper proxy that have the curveToken function otherwise it would revert when I'm not using forge-deploy, right?

**Comment by 0xCalibur** [comment]
can confirm it's now a new address and it doesn't exist yet
https://etherscan.io/address/0xecF3e645e5A6805C503fDCa00a14a84E881d9df1

<img width="694" alt="image" src="https://user-images.githubusercontent.com/92554750/236074158-cf5923cf-0d18-4c50-9a5c-fe49304940f8.png">

**Comment by wighawag** [comment]
using the template as suggested to make use of `new Contract(...` syntax works

See PR: https://github.com/Abracadabra-money/abracadabra-money-foundry/pull/73

This really suggests that forge is doing something weird when using assembly call for some reason, or is there something else in the way I make the assembly create call that is not correct ?

A minimal repo could help to ellucidate the problem. I would consider using the `new Contract(...` syntax in the default template but the thing I do not like about it is that we still need to compute the arg string and get the bytecode to save. so if this fails with the bytecode, then maybe the bytecode we get from forge is wrong and as such we will be saving wrong data.

**Comment by 0xCalibur** [comment]
No problem, here is a minimal repository reproducing the issue.

https://github.com/0xCalibur/forge-deploy-issue-2

**Comment by wighawag** [comment]
Thanks for that,

I figured the issue

It fails with forge-deploy because forge-deploy make sure to broadcast the tx


If you do 
```solidity
vm.broadcast();
return new Counter(wrapper);
```

It also fails

I guess this is because the account broadcasting has not right to deploy the wrapper

**Comment by 0xCalibur** [comment]
> Thanks for that,
> 
> I figured the issue
> 
> It fails with forge-deploy because forge-deploy make sure to broadcast the tx
> 
> If you do
> 
> ```solidity
> vm.broadcast();
> return new Counter(wrapper);
> ```
> 
> It also fails
> 
> I guess this is because the account broadcasting has not right to call curveToken or something ?

`.curveToken()` is a view, so the reason is probably something else ig

**Comment by wighawag** [comment]
I am closing this issue as the issue does not stem from forge-deploy which is intended to be used for broadcast

**Comment by 0xCalibur** [comment]
> I am closing this issue as the issue does not stem from forge-deploy which is intended to be used for broadcast
> 
> Feel free to open an issue if you think there are use case where broadcast is undesirable or if there are other issues related to it.
> 
> Thanks!

Hi, do you mean adding `--broadcast`, I updated the repo, where I did and it still fails with the same error

**Comment by wighawag** [comment]
No I am talking about the `vm.broadcast` call which make the next call a real tx

if you do not use it the tx will not happen on the network

and in you case, for some reason, if you use it it fails, whether you use forge-deploy or not

**Comment by wighawag** [comment]
Oh and for the demo repo, the reason it fails on the real network is that there is no vm.broadcast called for this line : https://github.com/0xCalibur/forge-deploy-issue-2/blob/f033944d079a733cb68389472594fc2d93f75d4f/script/Deploy.s.sol#LL13C8-L13C51

you need to call `vm.startBroadcast` and `vm.stopBroadcast` whenever you wan that tx actually hitting the network, see : https://book.getfoundry.sh/cheatcodes/start-broadcast

**Comment by 0xCalibur** [comment]
make sense, yeah I'm used to start/stop broadcast, been using it a lot over the year. It's just that I forgot that you use vm.broadcast and was used to have everything in between just broadcast, as an habit. Thx for shedding a light on this!

**Comment by wighawag** [comment]
OK, maybe it make sense to have an global option where broadcast is disabled in the deploy call
Tne templating system kind of solve this already but I ll think about it

**Comment by wighawag** [comment]
Hey @0xCalibur I am revisiting the setup in regard to broadcasting and would like your feedback: https://github.com/wighawag/forge-deploy/issues/3#issuecomment-1544786576

This would allow you to disable auto-broadcast
