### ISSUE TITLE
Broadcasting and pranks are not compatible

### ISSUE THREAD

**Issue by Ratimon** [wighawag/forge-deploy#3]
Hi, I have been using your tools (both `hadhat-deploy` and `forge-deploy`) for quite some times.  I really love how I can reuse my deploy script in test suites, reducing false positives and workload.

However, for forge-deploy, I cant use `vm.startprank` inside the `setup()` , so when deploying the contract that is inherited from `ownable` the wrong `owner` will be set , and this introduces false positive between the test suites and real environment.

From the developer perspective, I would love to see either:

1) `DeployScript` allows `vm.startBroadcast()` or  `vm.startBroadcast(deployerPrivateKey)` inside the deploy script

(btw I prefer `vm.startBroadcast()` as I can use HW to deploy the contract via `-t --sender @@DEPLOYER`. This will enhance security, as the private key is no longer required to be stored in the local machine. )

or

2) `vm.startprank()` is allowed inside the `setup()`

**Comment by wighawag** [comment]
agree, was expecting this kind of request to popup. I ll definitely fix that, hopefully very soon

re startPrank, can you give an example on how you would like to use it ?

**Comment by Ratimon** [comment]
I just would like to use it in a compatible way with foundry's cheat code of `startPrank()` :

`
    function setUp() external {
        vm.startPrank(owner);
        admin = new DeployProxyAdminScript().deploy();
        vm.stopPrank(  );
}
`

In my opinion, this is easily to read and accessible to someone who hasnt used it before.

No so sure how to implement this, there should be way to automatically stop broadcasting when entering `setUp()` function.

**Comment by wighawag** [comment]
Yes, make sense, the issue is that forge broadcast and prank are not really great for this. code cannot know if prank was set and so while I could call `stopPrank` I would not know if I need to reenable it at the end

This is something @fubhy mentioned here : https://github.com/foundry-rs/foundry/discussions/2787#discussioncomment-3405105 

But I thinking about more, I might be able to make the save function a internal call

because the issue is that currently when you call `deploy_MyContract` it need to have broadcast disabled before calling `save` so if you call `startBroadcast` beforehand it will be an issue there.

Having `save` and internal call will be a break change most likely but we need to get that right
ideally broadcast and prank would be better but let see where we can go. The issue make me think of https://github.com/wighawag/forge-deploy/issues/2 too where @0xCalibur was expecting the deploy function to not broadcast by default. Not sure about that yet but at least an option make sense

**Comment by wighawag** [comment]
I released an experimental version that get rid of external call altogether

See :https://github.com/wighawag/template-foundry/tree/forge-deploy-no-external-call

Note to play with it in your own setup, you need to use the npm package : `forge-deploy@experimental`

With that  you can use `vm.startBroadcast()` without fear of deploying/executing some forge-deploy specific stuff

the default deploy funciton will actually perform only one deployment so you can even use `vm.broadcast()` but as other library can provider their own more complex deploy function, you want want to take the habit of using `vm.startBroadcast`

By the way this is only if you want to take control of the broadcasting. and by default forge-deploy will broadcast on its own.

You can disable it to do as explained above via `DeployScript.setAutoBroadcast(false)`

see : https://github.com/wighawag/template-foundry/blob/543d70c1a44d5d0b99c27b4f0372b3cc64f0629f/test/GreetingsRegistry.t.sol#L13

let me know what you think of this

**Comment by 0xCalibur** [comment]
At the end, I just decided to go with the default template that broadcast every deploy_*. I must be honest: I'm not using it extensively yet, but I like the idea of having a toggle that disable/enable auto broadcast. Could make the script easier to read.

I'm not sure I understand the OP issue about pranking in a script as In my numerous tests I only prank inside the tests. And, also I just new Script() / run/deploy inside them to deploy. I think that just works vanilla. If that make sense....

I think I did something cool with our latest repo version (https://github.com/Abracadabra-money/abracadabra-money-contracts), sold a bit my soul there by including hardhat again. But I basically wanted to eliminate the Makefile and have the power and flexibilty of hardat-tasks again but keep the core with Foundry (test in solidity which I prefer and forge-deploy).

I did some function to forge-deploy deployment, parse it and load a contract.
So I can do multichain operations with ease....at the end I just like Javascript madness for scripting..

Anyway, just wanted to share my solution. Tell me what you think.

**Comment by wighawag** [comment]
nice, yes js is cool. I would also like to also use forge-deploy along hardhat. Plan to revisit hardhat-deploy for that at some point. You got some preliminary work here :)

**Comment by wighawag** [comment]
hmm, actually I realized a big issue with using internal call only and have the deployer a storage struct is that it is not shareable across contracts. 
That's not good. I ll probably need to revert to a Deploy contract and while you ll be able to disable broadcast entirely as an option, you'll not be able to manage broadcast differently. Need to spend more time thinking on it. I also created this issue which would make management possible : https://github.com/foundry-rs/foundry/issues/4927

**Comment by Ratimon** [comment]
> I released an experimental version that get rid of external call altogether
> 
> See :https://github.com/wighawag/template-foundry/tree/forge-deploy-no-external-call
> 
> Note to play with it in your own setup, you need to use the npm package : `forge-deploy@experimental`
> 
> With that you can use `vm.startBroadcast()` without fear of deploying/executing some forge-deploy specific stuff
> 
> the default deploy funciton will actually perform only one deployment so you can even use `vm.broadcast()` but as other library can provider their own more complex deploy function, you want want to take the habit of using `vm.startBroadcast`
> 
> By the way this is only if you want to take control of the broadcasting. and by default forge-deploy will broadcast on its own.
> 
> You can disable it to do as explained above via `DeployScript.setAutoBroadcast(false)`
> 
> see : https://github.com/wighawag/template-foundry/blob/543d70c1a44d5d0b99c27b4f0372b3cc64f0629f/test/GreetingsRegistry.t.sol#L13
> 
> let me know what you think of this

I have tried this. The new issue is the state is wrongly computed for some edge cases.

For example, if I gonna deploy a contract that is inherited from `ownable`, the relevant `owner` state is wrongly set to address of `DeployScript` not the actual `deployer`

No sure if this is relevant to your last comment.

**Comment by wighawag** [comment]
I realised prank only work in the current call context, which force me to handle it in the Deployer contract

I did that in v0.0.37

You can now just call `deployer.activatePrank(<address>)` and `deployer.deactivatePrank()`

see : https://github.com/wighawag/template-foundry/blob/c38515054b585baad0840776704c901fddab0207/test/GreetingsRegistry.t.sol#L38

this should solve your issue @Ratimon ?

**Comment by wighawag** [comment]
@0xCalibur in the new version you can do `deployer.setAutoBroadcast(false)` but note that you would not be able to wrap the deploy call in a `startBroadcast` as this would trigger some tx for the deployer.save calls until this feature:  https://github.com/foundry-rs/foundry/issues/4927 is implemented and used in forge-deploy

**Comment by Ratimon** [comment]
> foundry-rs/foundry#4927

Yes, It works well for me now.

I gently note that `deployer.activatePrank(<address>)` only works inside `setUp()` but  it does not work inside other functions (like test_*() ) . However, original `vm.prank` seems works. Just for possible improvement in your example: (https://github.com/wighawag/template-foundry/blob/c38515054b585baad0840776704c901fddab0207/test/GreetingsRegistry.t.sol#L38)

Appreciate for your fast support. This totally solves my issue.

**Comment by wighawag** [comment]
Cool

what do you mean by 
> I gently note that deployer.activatePrank(<address>) only works inside setUp() but it does not work inside other functions (like test_*() ) .

it works in my test, except I really should deactivate at the end of the test

**Comment by Ratimon** [comment]
I mean if I use `deployer.activatePrank()` in my test functions, my tests will fail. but `vm.start` doesnt fail my test.

In other words, I , for my test to be working, use `deployer.activatePrank()` only in my `setup()` and use `vm.start` in my test functions

I note that I havent deactivated the prank too.

**Comment by wighawag** [comment]
Oh, that will depend on the tests

`vm.prank` only affect the current call context so if there is a call calling something else, that something else will not be pranked

`deployer.activatePrank()` will only affect the create/create2 call made by the deployer function

so if your test fails, this is because of something else
