### ISSUE TITLE
read deployments from previous deployment scripts

### ISSUE THREAD

**Issue by Ratimon** [wighawag/forge-deploy#7]
It would be really nice for `forge-deploy` to support something like `deployments.read()` like `hardhat-deploy` does, so I can again re-use my past deployments in either future deploy script or in test suites across different chain networks .

I also note that I still love how `tags` and `dependency` work, but I still do not know the context to deal with them in solidity.

**Comment by 0xCalibur** [comment]
I did make something for it meanwhile if you're interested:
https://github.com/Abracadabra-money/abracadabra-money-contracts/blob/7180d51d4ffe673ab0f8341c47e3610417709363/hardhat.config.js#L123

**Comment by Ratimon** [comment]
Thanks for replying.

I have made it worked. I use `forge-deploy ` 's `deployer.getAddress` like:


`
        function deploy() external returns (Proxy) {

        proxyAdmin = deployer.getAddress('ProxyAdmin');

        return Proxy(
			deployer.deploy_Proxy(
				"L2OutputOracleProxy",
				proxyAdmin
			)
		);
`

But I still love to have `tag` and `dependencies` implemented so I dont have to re-write and re-import deployment script in test suites

**Comment by wighawag** [comment]
Was going to reply there is indeed the following method on the `deployer`:

```solidity
  /// @notice function that tell you whether a deployment already exists with that name
  /// @param name deployment's name to query
  /// @return exists whether the deployment exists or not
  function has(string memory name) external view returns (bool exists);

  /// @notice function that return the address of a deployment
  /// @param name deployment's name to query
  /// @return addr the deployment's address or the zero address
  function getAddress(string memory name) external view returns (address payable addr);

  /// @notice function that return the deployment (address, bytecode and args bytes used)
  /// @param name deployment's name to query
  /// @return deployment the deployment (with address zero if not existent)
  function get(string memory name) external view returns (Deployment memory deployment);
```

for tags and dependencies, let's make a different issue.

Not sure how this would work in solidity which is not dynamic. I guess this could be done with a specific executor that would in turn call `forge script....`
